### ISSUE TITLE
Observaciones Segundo Taller Practico:

### ISSUE THREAD

**Issue by AlexanderSiguenza** [KevinMartinezC/Taller2DSA_Farmacia#1]
Buen trabajo felicidades. Me gustaron los detalles UX/UI, imágenes y iconos, valoro su trabajo y dedicación

**Comment by KevinMartinezC** [comment]
> Buen trabajo felicidades. Me gustaron los detalles UX/UI, imágenes y iconos, valoro su trabajo y dedicación

Gracias Ing por sus observaciones. ¿Cuál sería nuestra nota en este taller?

**Comment by AlexanderSiguenza** [comment]
> > Buen trabajo felicidades. Me gustaron los detalles UX/UI, imágenes y iconos, valoro su trabajo y dedicación
> 
> Gracias Ing por sus observaciones. ¿Cuál sería nuestra nota en este taller?

**Comment by AlexanderSiguenza** [comment]
> > Buen trabajo felicidades. Me gustaron los detalles UX/UI, imágenes y iconos, valoro su trabajo y dedicación
> 
> Gracias Ing por sus observaciones. ¿Cuál sería nuestra nota en este taller?

En un momento las publico, ya les comfirmo

**Comment by KevinMartinezC** [comment]
> > > Buen trabajo felicidades. Me gustaron los detalles UX/UI, imágenes y iconos, valoro su trabajo y dedicación
> > 
> > Gracias Ing por sus observaciones. ¿Cuál sería nuestra nota en este taller?
> 
> En un momento las publico, ya les comfirmo

Ok muchas gracias Ing.
